USE [master]
GO
drop database [QLY_NHANVIEN]
go
use master
go
/****** Object:  Database [QLY_NHANVIEN]    Script Date: 4/16/2024 2:42:42 PM ******/
CREATE DATABASE [QLY_NHANVIEN]
go

 CONTAINMENT = NONE ON  PRIMARY 
( NAME = N'QLY_NHANVIEN', FILENAME = N'D:\MINHNGHIHTPT\MSSQL16.SQLEXPRESS\MSSQL\DATA\QLY_NHANVIEN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLY_NHANVIEN_log', FILENAME = N'D:\MINHNGHIHTPT\MSSQL16.SQLEXPRESS\MSSQL\DATA\QLY_NHANVIEN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QLY_NHANVIEN] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLY_NHANVIEN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLY_NHANVIEN] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLY_NHANVIEN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLY_NHANVIEN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET  DISABLE_BROKER 
GO
ALTER DATABASE [QLY_NHANVIEN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLY_NHANVIEN] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QLY_NHANVIEN] SET  MULTI_USER 
GO
ALTER DATABASE [QLY_NHANVIEN] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLY_NHANVIEN] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLY_NHANVIEN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLY_NHANVIEN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QLY_NHANVIEN] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QLY_NHANVIEN] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QLY_NHANVIEN] SET QUERY_STORE = ON
GO
ALTER DATABASE [QLY_NHANVIEN] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QLY_NHANVIEN]
GO
/****** Object:  Table [dbo].[cinema_Quyen]    Script Date: 4/16/2024 2:42:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cinema_Quyen](
	[iMaQuyen] [int] NOT NULL,
	[TenQuyen] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[cinema_TaiKhoan]    Script Date: 4/16/2024 2:42:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cinema_TaiKhoan](
	[MaTK] [nchar](50) NOT NULL,
	[TaiKhoan] [nvarchar](50) NOT NULL,
	[MatKhau] [nvarchar](50) NULL,
	[FK_iMaQuyen] [int] NULL
) ON [PRIMARY]
GO
INSERT [dbo].[cinema_Quyen] ([iMaQuyen], [TenQuyen]) VALUES (1, N'Admin')
GO
INSERT [dbo].[cinema_Quyen] ([iMaQuyen], [TenQuyen]) VALUES (2, N'NhanVien')
GO
INSERT [dbo].[cinema_TaiKhoan] ([MaTK], [TaiKhoan], [MatKhau], [FK_iMaQuyen]) VALUES (N'123                                               ', N'admin', N'1', 1)
GO
INSERT [dbo].[cinema_TaiKhoan] ([MaTK], [TaiKhoan], [MatKhau], [FK_iMaQuyen]) VALUES (N'222                                               ', N'nhanvien', N'1', 2)
GO
/****** Object:  StoredProcedure [dbo].[proc_login]    Script Date: 4/16/2024 2:42:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[proc_login] @user nvarchar(50), @pass nvarchar(50)
as
begin
	select * from cinema_TaiKhoan where TaiKhoan = @user and MatKhau =@pass
end
GO
USE [master]
GO
ALTER DATABASE [QLY_NHANVIEN] SET  READ_WRITE 
GO

use [QLY_NHANVIEN]
go
select * from [cinema_TaiKhoan]
